apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.bar.service" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.bar.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.bar" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.bar.service" . }}-public
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.bar.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.bar" . }}
