receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:55680"

exporters:
  otlp:
    endpoint: $GRPC_TRACES_ENDPOINT_URL
    insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
