apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.machinesvc.service" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.machinesvc.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.machinesvc" . }}
