apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.cashdesk.service" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.cashdesk.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.cashdesk" . }}
