AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: The Coffee Bar App Lambda Functions
Resources:
  SweetsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: SweetsApi
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  CheckSweetsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: CheckSweetsApi
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  SweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sweets.lambda_handler
      Runtime: python3.8
      CodeUri: ./functions/sweets
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 35
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3ReadOnlyAccess
        - Statement:
              - Sid: AWSLambdaInvokeAndGetFunctionAccess
                Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                Resource:
                  - "*"
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL: HTTP_TRACES_URL
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          OTEL_SERVICE_NAME: lambda-SweetsFunction
          OTEL_RESOURCE_ATTRIBUTES: application=the-coffee-bar-app
          OTEL_TRACES_SAMPLER: always_on
      Layers:
        - !FindInMap [RegionLayers, !Ref "AWS::Region", layer]
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref SweetsApi
            Path: /
            Method: POST
  CheckSweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: check_sweets.get_sweets
      Runtime: python3.8
      CodeUri: ./functions/check_sweets
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 35
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Statement:
              - Sid: AWSLambdaInvokeAndGetFunctionAccess
                Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                Resource:
                  - "*"
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL: HTTP_TRACES_URL
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          OTEL_SERVICE_NAME: lambda‑CheckSweetsFunction
          OTEL_RESOURCE_ATTRIBUTES: application=the-coffee-bar-app
          OTEL_TRACES_SAMPLER: always_on
          OTEL_PROPAGATORS: xray
          INVOKE_FUNCTION_NAME: !Ref SweetsFunction
      Layers:
        - !FindInMap [RegionLayers, !Ref "AWS::Region", layer]
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref CheckSweetsApi
            Path: /
            Method: POST
Mappings:
  RegionLayers:
    ap-northeast-1:
      layer: "arn:aws:lambda:ap-northeast-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    ap-northeast-2:
      layer: "arn:aws:lambda:ap-northeast-2:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    ap-south-1:
      layer: "arn:aws:lambda:ap-south-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    ap-southeast-1:
      layer: "arn:aws:lambda:ap-southeast-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    ap-southeast-2:
      layer: "arn:aws:lambda:ap-southeast-2:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    ca-central-1:
      layer: "arn:aws:lambda:ca-central-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    eu-central-1:
      layer: "arn:aws:lambda:eu-central-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:2"
    eu-north-1:
      layer: "arn:aws:lambda:eu-north-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    eu-west-1:
      layer: "arn:aws:lambda:eu-west-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    eu-west-2:
      layer: "arn:aws:lambda:eu-west-2:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    eu-west-3:
      layer: "arn:aws:lambda:eu-west-3:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    sa-east-1:
      layer: "	arn:aws:lambda:sa-east-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    us-east-1:
      layer: "arn:aws:lambda:us-east-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    us-east-2:
      layer: "arn:aws:lambda:us-east-2:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:2"
    us-west-1:
      layer: "arn:aws:lambda:us-west-1:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
    us-west-2:
      layer: "arn:aws:lambda:us-west-2:663229565520:layer:sumologic-aws-distro-otel-col-python-lambda-layer:1"
Metadata:
  AWS::ServerlessRepo::Application:
    Name: The-Coffee-Bar-App-Functions
    Description: The Coffee Bar App
    Author: Sumologic, Mateusz 'mat' Rumian
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: ['opentelemetry', 'python38', 'the-coffee-bar']
    HomePageUrl: https://github.com/SumoLogic/the-coffee-bar
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/SumoLogic/the-coffee-bar/tree/main/applications/aws-lambdas
