AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: The Coffee Bar App Lambda Functions
Resources:
  CakesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: CakesApi
      TracingEnabled: false
      OpenApiVersion: 3.0.2
  CheckCakesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: CheckCakesApi
      TracingEnabled: false
      OpenApiVersion: 3.0.2
  CakesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cakes.lambda_handler
      Runtime: python3.9
      CodeUri: ./functions/cakes
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 35
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3ReadOnlyAccess
        - Statement:
              - Sid: AWSLambdaInvokeAndGetFunctionAccess
                Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                Resource:
                  - "*"
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL: HTTP_TRACES_URL
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          OTEL_SERVICE_NAME: lambdaCakesFunction
          OTEL_RESOURCE_ATTRIBUTES: !Sub 'application=the-coffee-bar-app-cspm,cloud.account.id=${AWS::AccountId}'
          OTEL_TRACES_SAMPLER: always_on
      Layers:
        - !FindInMap [RegionLayers, !Ref "AWS::Region", layer]
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref CakesApi
            Path: /
            Method: POST
  CheckCakesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: check_cakes.get_cakes
      Runtime: python3.9
      CodeUri: ./functions/check_cakes
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 35
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Statement:
              - Sid: AWSLambdaInvokeAndGetFunctionAccess
                Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                Resource:
                  - "*"
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL: HTTP_TRACES_URL
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          OTEL_SERVICE_NAME: lambdaCheckCakesFunction
          OTEL_RESOURCE_ATTRIBUTES: !Sub 'application=the-coffee-bar-app-cspm,cloud.account.id=${AWS::AccountId}'
          OTEL_TRACES_SAMPLER: always_on
          INVOKE_FUNCTION_URL: !Sub "https://${CakesApi}.execute-api.${AWS::Region}.amazonaws.com/CakesApi"
          INVOKE_FUNCTION_NAME: !Ref CakesFunction
      Layers:
        - !FindInMap [RegionLayers, !Ref "AWS::Region", layer]
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref CheckCakesApi
            Path: /
            Method: POST
Mappings:
  RegionLayers:
    ap-northeast-1:
      layer: "arn:aws:lambda:ap-northeast-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    ap-northeast-2:
      layer: "arn:aws:lambda:ap-northeast-2:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    ap-south-1:
      layer: "arn:aws:lambda:ap-south-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    ap-southeast-1:
      layer: "arn:aws:lambda:ap-southeast-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
    ap-southeast-2:
      layer: "arn:aws:lambda:ap-southeast-2:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    ca-central-1:
      layer: "arn:aws:lambda:ca-central-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
    eu-central-1:
      layer: "arn:aws:lambda:eu-central-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
    eu-north-1:
      layer: "arn:aws:lambda:eu-north-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    eu-west-1:
      layer: "arn:aws:lambda:eu-west-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    eu-west-2:
      layer: "arn:aws:lambda:eu-west-2:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
    eu-west-3:
      layer: "arn:aws:lambda:eu-west-3:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    sa-east-1:
      layer: "	arn:aws:lambda:sa-east-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    us-east-1:
      layer: "arn:aws:lambda:us-east-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:1"
    us-east-2:
      layer: "arn:aws:lambda:us-east-2:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
    us-west-1:
      layer: "arn:aws:lambda:us-west-1:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
    us-west-2:
      layer: "arn:aws:lambda:us-west-2:663229565520:layer:sumologic-otel-python-x86_64-ver-1-10-0:2"
Metadata:
  AWS::ServerlessRepo::Application:
    Name: The-Coffee-Bar-App-Functions
    Description: The Coffee Bar App
    Author: Sumo Logic, Mateusz 'mat' Rumian
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: ['opentelemetry', 'python39', 'the-coffee-bar']
    HomePageUrl: https://github.com/SumoLogic/the-coffee-bar
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/SumoLogic/the-coffee-bar/tree/main/applications/aws-lambdas
