AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  SweetsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: SweetsApi
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  CheckSweetsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: CheckSweetsApi
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  SweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SweetsFunction
      Handler: sweets.lambda_handler
      Runtime: python3.8
      CodeUri: ./functions/sweets
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Statement:
              - Sid: AWSLambdaInvokeFunctionAccess
                Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource:
                  - "*"
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL: SUMO_HTTP_TRACES_URL
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/adot-instrument
          OTEL_RESOURCE_ATTRIBUTES: service.name=lambda‑SweetsFunction
          OTEL_PROPAGATORS: aws_xray
      Layers:
        - !Ref AwsObservability
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref SweetsApi
            Path: /
            Method: POST
  CheckSweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CheckSweetsFunction
      Handler: check_sweets.get_sweets
      Runtime: python3.8
      CodeUri: ./functions/check_sweets
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Statement:
              - Sid: AWSLambdaInvokeFunctionAccess
                Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource:
                  - "*"
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SUMOLOGIC_HTTP_TRACES_ENDPOINT_URL: SUMO_HTTP_TRACES_URL
          OTEL_RESOURCE_ATTRIBUTES: service.name=lambda‑CheckSweetsFunction
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/adot-instrument
          SWEETS_URL: SWEETS_API_URL
          OTEL_PROPAGATORS: aws_xray
      Layers:
        - !Ref AwsObservability
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref CheckSweetsApi
            Path: /
            Method: POST
  AwsObservability:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-distro-for-opentelemetry-python-38-preview
      Description: Lambda AWS Observability Python38 layer.
      ContentUri: ./aws_observability
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AWS-Distro-for-OpenTelemetry-Python-38-Sample
    Description: AWS Distro for Opentelemetry Python38 Sample
    Author: aws-observability
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['opentelemetry', 'python38', 'sample']
    HomePageUrl: https://aws.amazon.com/products/management-and-governance/use-cases/monitoring-and-observability/
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/aws-observability/aws-otel-lambda/sample-apps/python-lambda