apiVersion: v1
entries:
  sumologic-the-coffee-bar:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-20T01:44:21.965893+05:30"
    description: A Helm chart for Kubernetes
    digest: b96e00063ca8bf5a2db5c0113fdf6696b547b031035ff8929f5162f24ec668e4
    name: sumologic-the-coffee-bar
    type: application
    urls:
    - packages/sumologic-the-coffee-bar-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-20T01:44:21.96417+05:30"
    description: A Helm chart for Kubernetes
    digest: c03f626506f75ad26f80d74e5f4c4cdc158f899935a1f7de9499e5f7ac7efb02
    name: sumologic-the-coffee-bar
    type: application
    urls:
    - packages/sumologic-the-coffee-bar-0.2.0.tgz
    version: 0.2.0
generated: "2023-06-20T01:44:21.962169+05:30"
