apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.coffeesvc.service" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.coffeesvc.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
    {{- if .Values.customLabels.coffeesvc.labels }}
    {{ toYaml .Values.customLabels.coffeesvc.labels | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.coffeesvc" . }}
