source "https://rubygems.org"

gem 'opentelemetry-sdk', '0.14.0'
gem 'opentelemetry-instrumentation-all', '0.14.0'
gem 'opentelemetry-exporter-otlp', '0.14.0'
gem 'sinatra'
gem 'sinatra-json'
gem 'net'
