apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.calculatorsvc.deployment" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.calculatorsvc.deployment" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
    {{- if .Values.customLabels.calculatorsvc.labels }}
    {{ toYaml .Values.customLabels.calculatorsvc.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount.calculatorsvc.replicas }}
  selector:
    matchLabels:
      app: {{ include "sumologic.thecoffeebar.selectorLabels.calculatorsvc" . }}
      {{- include "sumologic.thecoffeebar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations.calculatorsvc.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "sumologic.thecoffeebar.selectorLabels.calculatorsvc" . }}
        {{- include "sumologic.thecoffeebar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sumologic.thecoffeebar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostname: {{ template "sumologic.thecoffeebar.metadata.name.calculatorsvc.service" . }}
      containers:
        - name: calculator-svc
          securityContext:
            {{- toYaml .Values.securityContext.common | nindent 12 }}
          image: "{{ .Values.image.dotnet.repository }}:{{ .Values.image.dotnet.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- include "sumologic.thecoffeebar.command.calculatorsvc" . | nindent 12 }}
          env:
          {{- include "sumologic.thecoffeebar.envs.calculatorsvc" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          {{- if .Values.healthChecks.calculator.livenessProbe.enabled }}
          livenessProbe:
            exec:
              {{- toYaml .Values.healthChecks.calculator.livenessProbe.exec | nindent 14 }}
            periodSeconds: {{ .Values.healthChecks.calculator.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthChecks.calculator.livenessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.healthChecks.calculator.readinessProbe.enabled }}
          readinessProbe:
            exec:
              {{- toYaml .Values.healthChecks.calculator.readinessProbe.exec | nindent 14 }}
            periodSeconds: {{ .Values.healthChecks.calculator.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthChecks.calculator.readinessProbe.initialDelaySeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.calculatorsvc.common | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinityRule.calculatorsvc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podPriority.calculatorsvc.enabled }}
      priorityClassName: {{ .Values.podPriority.calculatorsvc.priorityClassName }}
      {{- end }}
