apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.postgres.volume" . }}
  labels:
    volume: {{ include "sumologic.thecoffeebar.selectorLabels.postgres.volume" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
    {{- if .Values.customLabels.postgres.labels }}
    {{ toYaml .Values.customLabels.postgres.labels | nindent 4 }}
    {{- end }}
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/the-coffee-bar"
