---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-coffeemachine
spec:
  concurrencyPolicy: Forbid
  schedule: '{{ .Values.crons.coffeemachine }}'
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 10
      activeDeadlineSeconds: 600 # timeout, makes most sense with
                                 # "waiting for rollout" variant specified below
      template:
        spec:
          serviceAccountName: deployment-restart # name of the service
                                                 # account configured above
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl # probably any kubectl image will do,
                                     # optionaly specify version, but this
                                     # should not be necessary, as long the
                                     # version of kubectl is new enough to
                                     # have `rollout restart`
              command:
                - 'kubectl'
                - '-n'
                - '{{ .Release.Namespace }}'
                - 'rollout'
                - 'restart'
                - 'deployment/{{ include "sumologic.thecoffeebar.metadata.name.coffeemachine.deployment" . }}'