# Default values for sumologic.thecoffeebar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  dotnet:
    repository: public.ecr.aws/a4t4y2n3/the-coffee-bar
    tag: calculator-dotnet-1.1.0-1.0.0rc7
  frontend:
    repository: public.ecr.aws/a4t4y2n3/the-coffee-bar
    tag: frontend-jsv0.0.1-ot0.24.0
  python:
    repository: public.ecr.aws/a4t4y2n3/the-coffee-bar
    tag: pythonAppsv0.1.1-ot1.7.1-0.26b1
  ruby:
    repository: public.ecr.aws/a4t4y2n3/the-coffee-bar
    tag: rubyAppsv0.0.1-ot1.0.0-0.21.3-0.20.5
  clicker:
    repository: public.ecr.aws/a4t4y2n3/the-coffee-bar
    tag: clicker-linux
  postgres:
    repository: postgres
    tag: 9.6.2-alpine

  pullPolicy: Always


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  ## Required to run browsers in headless mode
  clicker:
    capabilities:
      add:
        - SYS_ADMIN
  ## Required to run CPU Killer/Network Delay
  frontend:
    capabilities:
      add:
        - SYS_ADMIN
        - NET_ADMIN
  common: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  frontend:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 768Mi
  python:
    common:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 400Mi
  ruby:
    common:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 250Mi
  calculatorsvc:
    common:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 500Mi
  clicker:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

healthChecks:
  calculator:
    livenessProbe:
      enabled: false
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep dotnet | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep dotnet | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
  clicker:
    livenessProbe:
      enabled: false
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep node | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep node | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
  frontend:
    livenessProbe:
      enabled: false
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep npm | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
    readinessProbe:
        enabled: true
        exec:
          command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep npm | grep -v grep
        periodSeconds: 5
        initialDelaySeconds: 15
  pythonApps:
    livenessProbe:
      enabled: true
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep python | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep python | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
  rubyApps:
    livenessProbe:
      enabled: false
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep ruby | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      exec:
        command:
          - /bin/sh
          - -c
          - -e
          - |
            ps aux | grep ruby | grep -v grep
      periodSeconds: 5
      initialDelaySeconds: 15

nodeSelector: {}

tolerations: []

affinity: {}

envs:
  bar:
    OTEL_RESOURCE_ATTRIBUTES: "service.name=the-coffee-bar,application=the-coffee-bar-app"
    OTEL_PROPAGATORS: "xray,tracecontext,baggage"
  calculatorsvc:
    OTEL_RESOURCE_ATTRIBUTES: "service.name=calculator-svc,application=the-coffee-bar-app"
  cashdesk:
    OTEL_RESOURCE_ATTRIBUTES: "service.name=the-cashdesk,application=the-coffee-bar-app"
  clicker:
    DELAY: "5"
  coffeemachine:
    CRON: "0 * * * *" # Run every hour
    OTEL_RESOURCE_ATTRIBUTES: "service.name=the-coffee-machine,application=the-coffee-bar-app"
  coffeesvc:
    OTEL_RESOURCE_ATTRIBUTES: "service.name=coffee-svc,application=the-coffee-bar-app"
  frontend:
    REACT_APP_SERVICE_NAME: "the-coffee-bar-frontend"
    REACT_APP_APPLICATION_NAME: "the-coffee-bar-app"
    REACT_APP_DEFAULT_ATTRIBUTES: '{"peer.service":"the-coffee-bar"}'
    ## Envs to configure CPU Killer and Network Delay
    CRON: "0 * * * *" # Run every hour
    DURATION: "5" # for 5 minutes
    THREADS_NO: "475" # on 475 threads
    NETWORK_DELAY: "1" # with 1 second network delay
  machinesvc:
    OTEL_RESOURCE_ATTRIBUTES: "service.name=machine-svc,application=the-coffee-bar-app"
  postgres:
    POSTGRES_HOST_AUTH_METHOD: trust
  watersvc:
    OTEL_RESOURCE_ATTRIBUTES: "service.name=water-svc,application=the-coffee-bar-app"

crons:
  clicker: '0 */4 * * *' # cron spec of time, here, 4 o'clock
  postgres: '0 */8 * * *' # cron spec of time, here, 8 o'clock
  cashdesk: '0 */8 * * *' # cron spec of time, here, 8 o'clock

extras:
  otelColHostName: collection-sumologic-otelcol.sumologic
  lambdaSweetsUrl:
  rumColSourceUrl:
