# Default values for sumologic.thecoffeebar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  dotnet:
    repository: 246946804217.dkr.ecr.us-west-2.amazonaws.com/tracing-demo-java/tracing-demo-java
    tag: calculator-dotnet-1.1.0b4-1.0.0rc5
  frontend:
    repository: 246946804217.dkr.ecr.us-west-2.amazonaws.com/tracing-demo-java/tracing-demo-java
    tag: frontend-js-0.18.2
  python:
    repository: 246946804217.dkr.ecr.us-west-2.amazonaws.com/tracing-demo-java/tracing-demo-java
    tag: python-apps-1.3.0-0.22b0
  ruby:
    repository: 246946804217.dkr.ecr.us-west-2.amazonaws.com/tracing-demo-java/tracing-demo-java
    tag: ruby-apps-1.0.0rc2-0.19.0-0.20.1
  clicker:
    repository: 246946804217.dkr.ecr.us-west-2.amazonaws.com/tracing-demo-java/tracing-demo-java
    tag: clicker
  postgres:
    repository: postgres
    tag: 9.6.2-alpine

  pullPolicy: Always


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  clicker:
    capabilities:
      add:
        - SYS_ADMIN
  common: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  frontend:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 768Mi
  python:
    common:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 250Mi
  ruby:
    common:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 250Mi
  dotnet:
    common:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 250Mi
  clicker:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 250Mi

envs:
  frontend:
    - name: REACT_APP_COFFEE_BAR_URL
      value: "http://sumologic-the-coffee-bar-bar:8082/order"
    - name: REACT_APP_SUMO_OT_JS_URL
      value: "https://cdn-service.us2.sumologic.com/ui/js/thirdparty/sumologic-opentelemetry.js"
    - name: REACT_APP_SERVICE_NAME
      value: "sumo-the-coffee-bar-frontend"
    - name: REACT_APP_APPLICATION_NAME
      value: "sumo-the-coffee-bar-app"
    - name: REACT_APP_COLLECTION_SOURCE_URL
      value: RUM_ENDPOINT_URL
  bar:
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=the-coffee-bar,application=sumo-the-coffee-bar-app"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:4317"
    - name: OTEL_PROPAGATORS
      value: "aws_xray,tracecontext,baggage"
  cashdesk:
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=the-cashdesk,application=sumo-the-coffee-bar-app"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:4317"
  coffeemachine:
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=the-coffee-machine,application=sumo-the-coffee-bar-app"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:4317"
  machinesvc:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=machine-svc,application=sumo-the-coffee-bar-app,k8s.pod.ip=$(MY_POD_IP)"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:55681"
  watersvc:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=water-svc,application=sumo-the-coffee-bar-app,k8s.pod.ip=$(MY_POD_IP)"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:55681"
  coffeesvc:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=coffee-svc,application=sumo-the-coffee-bar-app,k8s.pod.ip=$(MY_POD_IP)"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:55681"
  dotnet:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=coffee-svc,application=sumo-the-coffee-bar-app"
    - name: EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://collection-sumologic-otelcol.sumologic:4317"
  clicker:
    - name: DELAY
      value: "5"
  postgres:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust

commands:
  extras:
    bar:
      sweetsUrl: CHECK_SWEETS_URL

healthChecks:
  pythonApps:
    livenessProbe:
      enabled: false
      periodSeconds: 300
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      periodSeconds: 300
      initialDelaySeconds: 15
  frontend:
    livenessProbe:
      enabled: false
      periodSeconds: 300
      initialDelaySeconds: 90
    readinessProbe:
        enabled: true
        periodSeconds: 300
        initialDelaySeconds: 60
  calculator:
    livenessProbe:
      enabled: false
      periodSeconds: 300
      initialDelaySeconds: 30
    readinessProbe:
      enabled: true
      periodSeconds: 300
      initialDelaySeconds: 30
  rubyApps:
    livenessProbe:
      enabled: false
      periodSeconds: 300
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      periodSeconds: 30
      initialDelaySeconds: 15

nodeSelector: {}

tolerations: []

affinity: {}
