version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  the-coffee-bar:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-coffee-bar
    hostname: the-coffee-bar
    ports:
      - 8082:8082
    command: ["opentelemetry-instrument", "python3", "src/bin/the_coffee_bar.py",
              "--host=the-coffee-bar", "--port=8082", "--coffeemachine-host=the-coffee-machine",
              "--coffeemachine-port=8083", "--cashdesk-host=the-cashdesk", "--cashdesk-port=8084"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=the-coffee-bar
  the-coffee-bar-ui:
    image: sumo/the-coffee-bar-app:js-apps
    container_name: the-coffee-bar-ui
    hostname: the-coffee-bar-ui
    ports:
      - 3001:3000
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
  the-coffee-machine:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-coffee-machine
    hostname: the-coffee-machine
    ports:
      - 8083:8083
    command: ["opentelemetry-instrument", "python3", "src/bin/the_coffee_machine.py",
              "--host=the-coffee-machine", "--port=8083", "--machine-svc-host=machine-svc",
              "--machine-svc-port=9090"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=the-coffee-machine
  the-cashdesk:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-cashdesk
    hostname: the-cashdesk
    ports:
      - 8084:8084
    command: ["opentelemetry-instrument", "python3", "src/bin/the_cashdesk.py",
              "--host=the-cashdesk", "--port=8084", "--calculator-host=calculator-svc", "--calculator-port=8090",
              "--connection-string=postgresql://account:account@postgres:5432/account"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=the-cashdesk
  the-coffee-lover:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-coffee-lover
    hostname: the-coffee-lover
    command: ["opentelemetry-instrument", "python3", "src/bin/the_coffee_lover.py",
              "--host=the-coffee-bar", "--port=8082", "--ratio=5"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=the-coffee-lover
  machine-svc:
    image: sumo/the-coffee-bar-app:ruby-apps
    container_name: machine-svc
    hostname: machine-svc
    ports:
      - 9090:9090
    command: ["ruby", "/app/lib/machine.rb"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:55681
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=machine-svc
  coffee-svc:
    image: sumo/the-coffee-bar-app:ruby-apps
    container_name: coffee-svc
    hostname: coffee-svc
    ports:
      - 9091:9091
    command: ["ruby", "/app/lib/coffee.rb"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:55681
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=coffee-svc
  water-svc:
    image: sumo/the-coffee-bar-app:ruby-apps
    container_name: water-svc
    hostname: water-svc
    ports:
      - 9092:9092
    command: ["ruby", "/app/lib/water.rb"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:55681
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=water-svc
  calculator-svc:
    image: sumo/the-coffee-bar-app:dotnet-core-calculator-svc
    container_name: calculator-svc
    hostname: calculator-svc
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otelcol:4317
      - SERVICE_NAME=calculator-svc
      - SERVER_ENDPOINT=http://calculator-svc:8090
    ports:
      - 8090:8090
  otelcol:
    image: public.ecr.aws/sumologic/opentelemetry-collector:latest
    container_name: otelcol
    hostname: otelcol
    command: ["--config=/etc/otel-collector-config_otlp.yaml"]
    volumes:
        - ./otelcol.yaml:/etc/otel-collector-config_otlp.yaml
    ports:
      - "6831:6831"
      - "14251:14251"
      - "4317:4317"
      - "55680:55680"
      - "55681:55681"
      - "14268:14268"
      - "9411:9411"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
    expose:
      - 16686
