apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.frontend.deployment" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.frontend.deployment" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
    {{- if .Values.customLabels.frontend.labels }}
    {{ toYaml .Values.customLabels.frontend.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "sumologic.thecoffeebar.selectorLabels.frontend" . }}
      {{- include "sumologic.thecoffeebar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "sumologic.thecoffeebar.selectorLabels.frontend" . }}
        {{- include "sumologic.thecoffeebar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sumologic.thecoffeebar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostname: {{ template "sumologic.thecoffeebar.metadata.name.frontend.service" . }}
      containers:
        - name: the-coffee-bar-frontend
          securityContext:
            {{- toYaml .Values.securityContext.frontend | nindent 12 }}
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- include "sumologic.thecoffeebar.command.frontend" . | nindent 12 }}
          env:
          {{- include "sumologic.thecoffeebar.envs.frontend" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.healthChecks.frontend.livenessProbe.enabled }}
          livenessProbe:
            exec:
              {{- toYaml .Values.healthChecks.frontend.livenessProbe.exec | nindent 14 }}
            periodSeconds: {{ .Values.healthChecks.frontend.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthChecks.frontend.livenessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.healthChecks.frontend.readinessProbe.enabled }}
          readinessProbe:
            exec:
              {{- toYaml .Values.healthChecks.frontend.readinessProbe.exec | nindent 14 }}
            periodSeconds: {{ .Values.healthChecks.frontend.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthChecks.frontend.readinessProbe.initialDelaySeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinityRule.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podPriority.frontend.enabled }}
      priorityClassName: {{ .Values.podPriority.frontend.priorityClassName }}
      {{- end }}
