apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.frontend.service" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.frontend.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
    {{- if .Values.customLabels.frontend.labels }}
    {{ toYaml .Values.customLabels.frontend.labels | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.frontend" . }}
---
{{- if .Values.loadBalancers.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.frontend.service" . }}-public
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.frontend.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.frontend" . }}
{{- end }}
