apiVersion: v1
kind: Service
metadata:
  name: {{ include "sumologic.thecoffeebar.metadata.name.coffeemachine.service" . }}
  labels:
    app: {{ include "sumologic.thecoffeebar.labels.app.coffeemachine.service" . }}
    {{- include "sumologic.thecoffeebar.labels.common" . | nindent 4 }}
    {{- if .Values.customLabels.coffeemachine.labels }}
    {{ toYaml .Values.customLabels.coffeemachine.labels | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: {{ include "sumologic.thecoffeebar.selectorLabels.coffeemachine" . }}
